/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import app.ApplicationContext;
import dto.DoctorProfileDto;
import dto.LoginRequest;
import dto.PatientCreateRequest;
import dto.PatientProfileDto;
import dto.SessionDto;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame extends javax.swing.JFrame {

    private int x, y;
    private final ApplicationContext applicationContext;

    public NewJFrame() {
        this(ApplicationContext.bootstrap());
    }

    public NewJFrame(ApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginRootPanel = new packagee.PanelRound();
        loginTitleBarPanel = new packagee.PanelRound();
        closeButton = new javax.swing.JButton();
        loginTabbedPane = new javax.swing.JTabbedPane();
        loginFormPanel = new packagee.PanelRound();
        loginTitleLabel = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JTextField();
        loginPasswordLabel = new javax.swing.JLabel();
        loginEnterButton = new javax.swing.JButton();
        patientRegisterPanel = new javax.swing.JPanel();
        patientRegisterFirstnameLabel = new javax.swing.JLabel();
        patientRegisterFirstnameField = new javax.swing.JTextField();
        patientRegisterLastnameLabel = new javax.swing.JLabel();
        patientRegisterLastnameField = new javax.swing.JTextField();
        patientRegisterIdLabel = new javax.swing.JLabel();
        patientRegisterIdField = new javax.swing.JTextField();
        patientRegisterGenderLabel = new javax.swing.JLabel();
        patientRegisterPhoneLabel = new javax.swing.JLabel();
        patientRegisterPhoneField = new javax.swing.JTextField();
        patientRegisterEmailLabel = new javax.swing.JLabel();
        patientRegisterEmailField = new javax.swing.JTextField();
        patientRegisterUsernameLabel = new javax.swing.JLabel();
        patientRegisterUsernameField = new javax.swing.JTextField();
        patientRegisterPasswordField = new javax.swing.JTextField();
        patientRegisterPasswordLabel = new javax.swing.JLabel();
        patientRegisterConfirmPasswordLabel = new javax.swing.JLabel();
        patientRegisterConfirmPasswordField = new javax.swing.JTextField();
        patientRegisterGenderComboBox = new javax.swing.JComboBox<>();
        patientRegisterSaveButton = new javax.swing.JButton();
        patientRegisterAddressLabel = new javax.swing.JLabel();
        patientRegisterAddressField = new javax.swing.JTextField();
        patientRegisterBirthdateLabel = new javax.swing.JLabel();
        patientRegisterBirthdateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        loginRootPanel.setRadius(50);

        loginTitleBarPanel.setRadius(50);
        loginTitleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        loginTitleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        closeButton.setText("X");
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.setFocusable(false);
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(loginTitleBarPanel);
        loginTitleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        loginTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        loginTitleLabel.setText("LOGIN");

        loginUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginUsernameLabel.setText("USERNAME");

        loginPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginPasswordLabel.setText("PASSWORD");

        loginEnterButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginEnterButton.setText("ENTER");
        loginEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(loginFormPanel);
        loginFormPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(loginTitleLabel)
                .addGap(481, 481, 481))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loginUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(loginEnterButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(loginTitleLabel)
                .addGap(74, 74, 74)
                .addComponent(loginUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(loginEnterButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        loginTabbedPane.addTab("Login", loginFormPanel);

        patientRegisterFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterFirstnameLabel.setText("Firstname");

        patientRegisterFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterLastnameLabel.setText("Lastname");

        patientRegisterLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterIdLabel.setText("ID");

        patientRegisterIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterGenderLabel.setText("Gender");

        patientRegisterPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterPhoneLabel.setText("Phone");

        patientRegisterPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterEmailLabel.setText("Email");

        patientRegisterEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterUsernameLabel.setText("User");

        patientRegisterUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterPasswordLabel.setText("Password");

        patientRegisterConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterConfirmPasswordLabel.setText("Password confirmation");

        patientRegisterConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        patientRegisterGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        patientRegisterSaveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterSaveButton.setText("Save");
        patientRegisterSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        patientRegisterAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterAddressLabel.setText("Address");

        patientRegisterAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientRegisterBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientRegisterBirthdateLabel.setText("Birthdate");

        patientRegisterBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(patientRegisterPanel);
        patientRegisterPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(patientRegisterPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientRegisterUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientRegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(patientRegisterUsernameLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(patientRegisterConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(patientRegisterSaveButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(patientRegisterConfirmPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(patientRegisterBirthdateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientRegisterBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(patientRegisterFirstnameLabel)
                                .addGap(34, 34, 34)
                                .addComponent(patientRegisterFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientRegisterLastnameLabel)
                            .addComponent(patientRegisterAddressLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(patientRegisterLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(patientRegisterIdLabel)
                                .addGap(30, 30, 30)
                                .addComponent(patientRegisterIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(patientRegisterGenderLabel)
                                .addGap(26, 26, 26)
                                .addComponent(patientRegisterGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(patientRegisterAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(patientRegisterPhoneLabel)
                                .addGap(18, 18, 18)
                                .addComponent(patientRegisterPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientRegisterEmailLabel)
                                .addGap(18, 18, 18)
                                .addComponent(patientRegisterEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientRegisterFirstnameLabel)
                    .addComponent(patientRegisterFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientRegisterLastnameLabel)
                    .addComponent(patientRegisterLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientRegisterIdLabel)
                    .addComponent(patientRegisterIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientRegisterGenderLabel)
                    .addComponent(patientRegisterGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientRegisterBirthdateLabel)
                        .addComponent(patientRegisterBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(patientRegisterAddressLabel)
                        .addComponent(patientRegisterAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(patientRegisterPhoneLabel)
                        .addComponent(patientRegisterPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientRegisterEmailLabel)
                        .addComponent(patientRegisterEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(patientRegisterUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientRegisterUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patientRegisterPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientRegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientRegisterConfirmPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientRegisterConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(patientRegisterSaveButton)
                .addGap(42, 42, 42))
        );

        loginTabbedPane.addTab("Patient register", patientRegisterPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(loginRootPanel);
        loginRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(loginTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(loginTitleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginRequest request = new LoginRequest(loginUsernameField.getText(), loginPasswordField.getText());
        Response<SessionDto> response = applicationContext.getAuthController().login(request);
        showResponse(response);
        if (response.isSuccess()) {
            clearLoginFields();
            openViewForSession(response.getData());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PatientCreateRequest request = new PatientCreateRequest(
                patientRegisterIdField.getText(),
                patientRegisterUsernameField.getText(),
                patientRegisterFirstnameField.getText(),
                patientRegisterLastnameField.getText(),
                patientRegisterPasswordField.getText(),
                patientRegisterConfirmPasswordField.getText(),
                patientRegisterEmailField.getText(),
                patientRegisterBirthdateField.getText(),
                patientRegisterGenderComboBox.getSelectedIndex() == 2,
                patientRegisterPhoneField.getText(),
                patientRegisterAddressField.getText()
        );
        Response<PatientProfileDto> response = applicationContext.getPatientController().createPatient(request);
        showResponse(response);
        if (response.isSuccess()) {
            clearPatientRegistrationFields();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void openViewForSession(SessionDto session) {
        if ("ADMIN".equals(session.getRole())) {
            openFrame(new NewJFrame11(applicationContext, session));
            return;
        }
        if ("DOCTOR".equals(session.getRole())) {
            Response<DoctorProfileDto> response = applicationContext.getDoctorController()
                    .getDoctorProfile(String.valueOf(session.getId()));
            if (response.isSuccess()) {
                openFrame(new NewJFrame111(applicationContext, session, response.getData()));
            } else {
                showResponse(response);
            }
            return;
        }

        Response<PatientProfileDto> response = applicationContext.getPatientController()
                .getPatientProfile(String.valueOf(session.getId()));
        if (response.isSuccess()) {
            openFrame(new NewJFrame1(applicationContext, session, response.getData()));
        } else {
            showResponse(response);
        }
    }

    private void openFrame(JFrame frame) {
        this.setVisible(false);
        frame.setVisible(true);
        this.dispose();
    }

    private void showResponse(Response<?> response) {
        JOptionPane.showMessageDialog(this, response.getMessage());
    }

    private void clearLoginFields() {
        loginUsernameField.setText("");
        loginPasswordField.setText("");
    }

    private void clearPatientRegistrationFields() {
        patientRegisterFirstnameField.setText("");
        patientRegisterLastnameField.setText("");
        patientRegisterIdField.setText("");
        patientRegisterPhoneField.setText("");
        patientRegisterEmailField.setText("");
        patientRegisterUsernameField.setText("");
        patientRegisterPasswordField.setText("");
        patientRegisterConfirmPasswordField.setText("");
        patientRegisterAddressField.setText("");
        patientRegisterBirthdateField.setText("");
        patientRegisterGenderComboBox.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton loginEnterButton;
    private javax.swing.JButton patientRegisterSaveButton;
    private javax.swing.JComboBox<String> patientRegisterGenderComboBox;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JLabel patientRegisterUsernameLabel;
    private javax.swing.JLabel patientRegisterPasswordLabel;
    private javax.swing.JLabel patientRegisterConfirmPasswordLabel;
    private javax.swing.JLabel patientRegisterAddressLabel;
    private javax.swing.JLabel patientRegisterBirthdateLabel;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JLabel patientRegisterFirstnameLabel;
    private javax.swing.JLabel patientRegisterLastnameLabel;
    private javax.swing.JLabel patientRegisterIdLabel;
    private javax.swing.JLabel patientRegisterGenderLabel;
    private javax.swing.JLabel patientRegisterPhoneLabel;
    private javax.swing.JLabel patientRegisterEmailLabel;
    private javax.swing.JPanel patientRegisterPanel;
    private javax.swing.JTabbedPane loginTabbedPane;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JTextField patientRegisterConfirmPasswordField;
    private javax.swing.JTextField patientRegisterAddressField;
    private javax.swing.JTextField patientRegisterBirthdateField;
    private javax.swing.JTextField loginPasswordField;
    private javax.swing.JTextField patientRegisterFirstnameField;
    private javax.swing.JTextField patientRegisterLastnameField;
    private javax.swing.JTextField patientRegisterIdField;
    private javax.swing.JTextField patientRegisterPhoneField;
    private javax.swing.JTextField patientRegisterEmailField;
    private javax.swing.JTextField patientRegisterUsernameField;
    private javax.swing.JTextField patientRegisterPasswordField;
    private packagee.PanelRound loginRootPanel;
    private packagee.PanelRound loginTitleBarPanel;
    private packagee.PanelRound loginFormPanel;
    // End of variables declaration//GEN-END:variables
}
