/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import app.ApplicationContext;
import dto.DoctorCreateRequest;
import dto.DoctorOptionDto;
import dto.DoctorProfileDto;
import dto.PatientOptionDto;
import dto.PatientProfileDto;
import dto.SessionDto;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame11 extends javax.swing.JFrame {

    private int x, y;
    private final ApplicationContext applicationContext;
    private final SessionDto currentSession;

    public NewJFrame11(ApplicationContext applicationContext, SessionDto currentSession) {
        this.applicationContext = applicationContext;
        this.currentSession = currentSession;
        initComponents();
        loadUserOptions();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminRootPanel = new packagee.PanelRound();
        adminTitleBarPanel = new packagee.PanelRound();
        adminCloseButton = new javax.swing.JButton();
        adminTitleLabel = new javax.swing.JLabel();
        adminContentPanel = new packagee.PanelRound();
        openDoctorViewButton = new javax.swing.JButton();
        openPatientViewButton = new javax.swing.JButton();
        doctorRegisterFirstnameLabel = new javax.swing.JLabel();
        doctorRegisterFirstnameField = new javax.swing.JTextField();
        doctorRegisterLastnameLabel = new javax.swing.JLabel();
        doctorRegisterLastnameField = new javax.swing.JTextField();
        doctorRegisterIdLabel = new javax.swing.JLabel();
        doctorRegisterIdField = new javax.swing.JTextField();
        doctorRegisterSpecialtyLabel = new javax.swing.JLabel();
        doctorRegisterLicenseLabel = new javax.swing.JLabel();
        doctorRegisterLicenseField = new javax.swing.JTextField();
        doctorRegisterOfficeLabel = new javax.swing.JLabel();
        doctorRegisterOfficeField = new javax.swing.JTextField();
        doctorRegisterUsernameLabel = new javax.swing.JLabel();
        doctorRegisterUsernameField = new javax.swing.JTextField();
        doctorRegisterPasswordLabel = new javax.swing.JLabel();
        doctorRegisterPasswordField = new javax.swing.JTextField();
        doctorRegisterConfirmPasswordLabel = new javax.swing.JLabel();
        doctorRegisterConfirmPasswordField = new javax.swing.JTextField();
        doctorRegisterSpecialtyComboBox = new javax.swing.JComboBox<>();
        doctorRegisterSaveButton = new javax.swing.JButton();
        adminDoctorSeparator = new javax.swing.JSeparator();
        doctorProfileComboBox = new javax.swing.JComboBox<>();
        doctorProfileComboLabel = new javax.swing.JLabel();
        patientProfileComboLabel = new javax.swing.JLabel();
        patientProfileComboBox = new javax.swing.JComboBox<>();
        adminPatientSeparator = new javax.swing.JSeparator();
        adminLogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        adminRootPanel.setRadius(50);

        adminTitleBarPanel.setRadius(50);
        adminTitleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        adminTitleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        adminCloseButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminCloseButton.setText("X");
        adminCloseButton.setBorderPainted(false);
        adminCloseButton.setContentAreaFilled(false);
        adminCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminCloseButton.setFocusable(false);
        adminCloseButton.setRequestFocusEnabled(false);
        adminCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        adminTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        adminTitleLabel.setText("ADMIN VIEW");

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(adminTitleBarPanel);
        adminTitleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(adminTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminCloseButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adminCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminTitleLabel))
        );

        openDoctorViewButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        openDoctorViewButton.setText("DOCTOR VIEW");
        openDoctorViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        openPatientViewButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        openPatientViewButton.setText("PATIENT VIEW");
        openPatientViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        doctorRegisterFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterFirstnameLabel.setText("Firstname");

        doctorRegisterFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterLastnameLabel.setText("Lastname");

        doctorRegisterLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterIdLabel.setText("ID");

        doctorRegisterIdField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterSpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterSpecialtyLabel.setText("Specialty");

        doctorRegisterLicenseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterLicenseLabel.setText("License Number");

        doctorRegisterLicenseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterOfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterOfficeLabel.setText("Assigned office");

        doctorRegisterOfficeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterUsernameLabel.setText("User");

        doctorRegisterUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterPasswordLabel.setText("Password");

        doctorRegisterPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterConfirmPasswordLabel.setText("Password confirmation");

        doctorRegisterConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorRegisterSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        doctorRegisterSaveButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorRegisterSaveButton.setText("Save");
        doctorRegisterSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        adminDoctorSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        doctorProfileComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorProfileComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        doctorProfileComboLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorProfileComboLabel.setText("Doctor");

        patientProfileComboLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientProfileComboLabel.setText("Patient");

        patientProfileComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientProfileComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        adminPatientSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        adminLogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        adminLogoutButton.setText("Logout");
        adminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(adminContentPanel);
        adminContentPanel.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(doctorRegisterSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctorRegisterFirstnameLabel)
                                    .addComponent(doctorRegisterSpecialtyLabel))
                                .addGap(18, 18, 18)
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorRegisterSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorRegisterLicenseLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorRegisterLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorRegisterFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(doctorRegisterLastnameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorRegisterLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorRegisterIdLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorRegisterIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addComponent(doctorRegisterOfficeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(doctorRegisterOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorRegisterUsernameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorRegisterUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorRegisterPasswordLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorRegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addComponent(doctorRegisterConfirmPasswordLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(doctorRegisterConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(333, 333, 333)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openDoctorViewButton)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(doctorProfileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRound3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(doctorProfileComboLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminLogoutButton)
                        .addGap(318, 318, 318)))
                .addComponent(adminDoctorSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openPatientViewButton)
                            .addGroup(panelRound3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(patientProfileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(patientProfileComboLabel)))
                .addGap(88, 88, 88))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(adminPatientSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(adminDoctorSeparator)
                .addContainerGap())
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorRegisterFirstnameLabel)
                    .addComponent(doctorRegisterFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorRegisterLastnameLabel)
                    .addComponent(doctorRegisterLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorRegisterIdLabel)
                    .addComponent(doctorRegisterIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorRegisterSpecialtyLabel)
                    .addComponent(doctorRegisterSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorRegisterLicenseLabel)
                    .addComponent(doctorRegisterLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorRegisterOfficeLabel)
                    .addComponent(doctorRegisterOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorRegisterUsernameLabel)
                            .addComponent(doctorRegisterUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorRegisterPasswordLabel)
                            .addComponent(doctorRegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorRegisterConfirmPasswordLabel)
                            .addComponent(doctorRegisterConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(doctorProfileComboLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorProfileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(openDoctorViewButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(doctorRegisterSaveButton)
                .addGap(123, 123, 123)
                .addComponent(adminLogoutButton)
                .addGap(38, 38, 38))
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(patientProfileComboLabel)
                .addGap(18, 18, 18)
                .addComponent(patientProfileComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(openPatientViewButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(adminPatientSeparator)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(adminRootPanel);
        adminRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminTitleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(adminTitleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DoctorCreateRequest request = new DoctorCreateRequest(
                doctorRegisterIdField.getText(),
                doctorRegisterUsernameField.getText(),
                doctorRegisterFirstnameField.getText(),
                doctorRegisterLastnameField.getText(),
                doctorRegisterPasswordField.getText(),
                doctorRegisterConfirmPasswordField.getText(),
                doctorRegisterSpecialtyComboBox.getItemAt(doctorRegisterSpecialtyComboBox.getSelectedIndex()),
                doctorRegisterLicenseField.getText(),
                doctorRegisterOfficeField.getText()
        );
        Response<DoctorProfileDto> response = applicationContext.getDoctorController()
                .createDoctor(request, currentSession);
        showResponse(response);
        if (response.isSuccess()) {
            clearDoctorRegistrationFields();
            loadUserOptions();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Response<DoctorProfileDto> response = applicationContext.getDoctorController()
                .getDoctorProfile(doctorProfileComboBox.getItemAt(doctorProfileComboBox.getSelectedIndex()));
        if (response.isSuccess()) {
            openFrame(new NewJFrame111(applicationContext, currentSession, response.getData()));
        } else {
            showResponse(response);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        openFrame(new NewJFrame(applicationContext));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Response<PatientProfileDto> response = applicationContext.getPatientController()
                .getPatientProfile(patientProfileComboBox.getItemAt(patientProfileComboBox.getSelectedIndex()));
        if (response.isSuccess()) {
            openFrame(new NewJFrame1(applicationContext, currentSession, response.getData()));
        } else {
            showResponse(response);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loadUserOptions() {
        doctorProfileComboBox.removeAllItems();
        doctorProfileComboBox.addItem("Select one");
        Response<java.util.List<DoctorOptionDto>> doctors = applicationContext.getTableDataController().getDoctorOptions();
        if (doctors.isSuccess()) {
            for (DoctorOptionDto doctor : doctors.getData()) {
                doctorProfileComboBox.addItem(String.valueOf(doctor.getId()));
            }
        }

        patientProfileComboBox.removeAllItems();
        patientProfileComboBox.addItem("Select one");
        Response<java.util.List<PatientOptionDto>> patients = applicationContext.getTableDataController().getPatientOptions();
        if (patients.isSuccess()) {
            for (PatientOptionDto patient : patients.getData()) {
                patientProfileComboBox.addItem(String.valueOf(patient.getId()));
            }
        }
    }

    private void openFrame(JFrame frame) {
        this.setVisible(false);
        frame.setVisible(true);
        this.dispose();
    }

    private void showResponse(Response<?> response) {
        JOptionPane.showMessageDialog(this, response.getMessage());
    }

    private void clearDoctorRegistrationFields() {
        doctorRegisterFirstnameField.setText("");
        doctorRegisterLastnameField.setText("");
        doctorRegisterIdField.setText("");
        doctorRegisterLicenseField.setText("");
        doctorRegisterOfficeField.setText("");
        doctorRegisterUsernameField.setText("");
        doctorRegisterPasswordField.setText("");
        doctorRegisterConfirmPasswordField.setText("");
        doctorRegisterSpecialtyComboBox.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminCloseButton;
    private javax.swing.JButton adminLogoutButton;
    private javax.swing.JButton openDoctorViewButton;
    private javax.swing.JButton openPatientViewButton;
    private javax.swing.JButton doctorRegisterSaveButton;
    private javax.swing.JComboBox<String> doctorRegisterSpecialtyComboBox;
    private javax.swing.JComboBox<String> doctorProfileComboBox;
    private javax.swing.JComboBox<String> patientProfileComboBox;
    private javax.swing.JLabel adminTitleLabel;
    private javax.swing.JLabel doctorRegisterUsernameLabel;
    private javax.swing.JLabel doctorRegisterPasswordLabel;
    private javax.swing.JLabel doctorRegisterConfirmPasswordLabel;
    private javax.swing.JLabel doctorProfileComboLabel;
    private javax.swing.JLabel patientProfileComboLabel;
    private javax.swing.JLabel doctorRegisterFirstnameLabel;
    private javax.swing.JLabel doctorRegisterLastnameLabel;
    private javax.swing.JLabel doctorRegisterIdLabel;
    private javax.swing.JLabel doctorRegisterSpecialtyLabel;
    private javax.swing.JLabel doctorRegisterLicenseLabel;
    private javax.swing.JLabel doctorRegisterOfficeLabel;
    private javax.swing.JSeparator adminDoctorSeparator;
    private javax.swing.JSeparator adminPatientSeparator;
    private javax.swing.JTextField doctorRegisterConfirmPasswordField;
    private javax.swing.JTextField doctorRegisterFirstnameField;
    private javax.swing.JTextField doctorRegisterLastnameField;
    private javax.swing.JTextField doctorRegisterIdField;
    private javax.swing.JTextField doctorRegisterLicenseField;
    private javax.swing.JTextField doctorRegisterOfficeField;
    private javax.swing.JTextField doctorRegisterUsernameField;
    private javax.swing.JTextField doctorRegisterPasswordField;
    private packagee.PanelRound adminRootPanel;
    private packagee.PanelRound adminTitleBarPanel;
    private packagee.PanelRound adminContentPanel;
    // End of variables declaration//GEN-END:variables
}
