/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import app.ApplicationContext;
import dto.AppointmentRequest;
import dto.AppointmentTableDto;
import dto.DoctorOptionDto;
import dto.HospitalizationRequest;
import dto.PatientProfileDto;
import dto.PatientUpdateRequest;
import dto.SessionDto;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private int x, y;
    private final ApplicationContext applicationContext;
    private final SessionDto currentSession;
    private PatientProfileDto patientProfile;

    public NewJFrame1(ApplicationContext applicationContext, SessionDto currentSession,
            PatientProfileDto patientProfile) {
        this.applicationContext = applicationContext;
        this.currentSession = currentSession;
        this.patientProfile = patientProfile;
        initComponents();
        patientBackButton.setVisible("ADMIN".equals(currentSession.getRole()));
        loadPatientProfile();
        loadViewData();
        applicationContext.getEventPublisher().addListener(this::loadViewData);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientRootPanel = new packagee.PanelRound();
        patientTitleBarPanel = new packagee.PanelRound();
        patientCloseButton = new javax.swing.JButton();
        patientTitleLabel = new javax.swing.JLabel();
        patientBackButton = new javax.swing.JButton();
        patientTabbedPane = new javax.swing.JTabbedPane();
        patientAppointmentsPanel = new javax.swing.JPanel();
        appointmentsTableScrollPane = new javax.swing.JScrollPane();
        patientAppointmentsTable = new javax.swing.JTable();
        refreshAppointmentsButton = new javax.swing.JButton();
        patientLogoutButton = new javax.swing.JButton();
        patientProfilePanel = new javax.swing.JPanel();
        patientFirstnameLabel = new javax.swing.JLabel();
        patientFirstnameField = new javax.swing.JTextField();
        patientLastnameLabel = new javax.swing.JLabel();
        patientLastnameField = new javax.swing.JTextField();
        patientBirthdateLabel = new javax.swing.JLabel();
        patientBirthdateField = new javax.swing.JTextField();
        patientGenderLabel = new javax.swing.JLabel();
        patientEmailLabel = new javax.swing.JLabel();
        patientEmailField = new javax.swing.JTextField();
        patientPhoneLabel = new javax.swing.JLabel();
        patientPhoneField = new javax.swing.JTextField();
        patientAddressLabel = new javax.swing.JLabel();
        patientAddressField = new javax.swing.JTextField();
        patientPasswordField = new javax.swing.JTextField();
        patientPasswordLabel = new javax.swing.JLabel();
        patientConfirmPasswordLabel = new javax.swing.JLabel();
        patientConfirmPasswordField = new javax.swing.JTextField();
        savePatientProfileButton = new javax.swing.JButton();
        patientUsernameLabel = new javax.swing.JLabel();
        patientUsernameField = new javax.swing.JTextField();
        patientGenderComboBox = new javax.swing.JComboBox<>();
        patientRequestPanel = new javax.swing.JPanel();
        appointmentRequestTitleLabel = new javax.swing.JLabel();
        searchBySpecialtyRadioButton = new javax.swing.JRadioButton();
        searchByDoctorRadioButton = new javax.swing.JRadioButton();
        patientProfileSeparator = new javax.swing.JSeparator();
        appointmentDateLabel = new javax.swing.JLabel();
        appointmentDateField = new javax.swing.JTextField();
        appointmentTimeField = new javax.swing.JTextField();
        appointmentTimeLabel = new javax.swing.JLabel();
        appointmentTypeLabel = new javax.swing.JLabel();
        appointmentReasonLabel = new javax.swing.JLabel();
        appointmentTypeComboBox = new javax.swing.JComboBox<>();
        requestAppointmentButton = new javax.swing.JButton();
        requestSeparator = new javax.swing.JSeparator();
        hospitalizationRequestTitleLabel = new javax.swing.JLabel();
        hospitalizationReasonLabel = new javax.swing.JLabel();
        hospitalizationDoctorLabel = new javax.swing.JLabel();
        hospitalizationDoctorComboBox = new javax.swing.JComboBox<>();
        hospitalizationAdmissionDateField = new javax.swing.JTextField();
        hospitalizationAdmissionDateLabel = new javax.swing.JLabel();
        hospitalizationRoomTypeLabel = new javax.swing.JLabel();
        roomTypeComboBox = new javax.swing.JComboBox<>();
        hospitalizationObservationsLabel = new javax.swing.JLabel();
        hospitalizationObservationsScrollPane = new javax.swing.JScrollPane();
        hospitalizationObservationsArea = new javax.swing.JTextArea();
        requestHospitalizationButton = new javax.swing.JButton();
        cancelAppointmentTitleLabel = new javax.swing.JLabel();
        cancelAppointmentIdLabel = new javax.swing.JLabel();
        cancelAppointmentObservationsLabel = new javax.swing.JLabel();
        cancelObservationsScrollPane = new javax.swing.JScrollPane();
        cancelAppointmentObservationsArea = new javax.swing.JTextArea();
        cancelAppointmentButton = new javax.swing.JButton();
        hospitalizationReasonScrollPane = new javax.swing.JScrollPane();
        hospitalizationReasonArea = new javax.swing.JTextArea();
        appointmentReasonScrollPane = new javax.swing.JScrollPane();
        appointmentReasonArea = new javax.swing.JTextArea();
        cancelAppointmentComboBox = new javax.swing.JComboBox<>();
        appointmentDoctorOrSpecialtyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        patientRootPanel.setRadius(50);

        patientTitleBarPanel.setRadius(50);
        patientTitleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        patientTitleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        patientCloseButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientCloseButton.setText("X");
        patientCloseButton.setBorderPainted(false);
        patientCloseButton.setContentAreaFilled(false);
        patientCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        patientCloseButton.setFocusable(false);
        patientCloseButton.setRequestFocusEnabled(false);
        patientCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        patientTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        patientTitleLabel.setText("PATIENT VIEW");

        patientBackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientBackButton.setText("Back");
        patientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(patientTitleBarPanel);
        patientTitleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(patientTitleLabel)
                .addGap(29, 29, 29)
                .addComponent(patientBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientCloseButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(patientCloseButton))
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientBackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(patientTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        patientAppointmentsTable.setAutoCreateRowSorter(true);
        patientAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentsTableScrollPane.setViewportView(patientAppointmentsTable);

        refreshAppointmentsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        refreshAppointmentsButton.setText("Refresh");
        refreshAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        patientLogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLogoutButton.setText("Logout");
        patientLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(patientAppointmentsPanel);
        patientAppointmentsPanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(appointmentsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(refreshAppointmentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientLogoutButton)
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(appointmentsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshAppointmentsButton)
                    .addComponent(patientLogoutButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        patientTabbedPane.addTab("Appointment history", patientAppointmentsPanel);

        patientFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientFirstnameLabel.setText("Firstname");

        patientFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLastnameLabel.setText("Lastname");

        patientLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientBirthdateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientBirthdateLabel.setText("Birthdate");

        patientBirthdateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientGenderLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientGenderLabel.setText("Gender");

        patientEmailLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientEmailLabel.setText("Email");

        patientEmailField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPhoneLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPhoneLabel.setText("Phone");

        patientPhoneField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientAddressLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientAddressLabel.setText("Address");

        patientAddressField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientPasswordLabel.setText("Password");

        patientConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientConfirmPasswordLabel.setText("Password confirmation");

        patientConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        savePatientProfileButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        savePatientProfileButton.setText("Save");
        savePatientProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        patientUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientUsernameLabel.setText("User");

        patientUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        patientGenderComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientGenderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(patientProfilePanel);
        patientProfilePanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(patientFirstnameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(patientLastnameLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientPhoneLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(patientAddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientBirthdateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientGenderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(patientEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(patientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(savePatientProfileButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(patientConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(patientConfirmPasswordLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(patientPasswordLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(patientUsernameLabel)))
                            .addComponent(patientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFirstnameLabel)
                    .addComponent(patientFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientLastnameLabel)
                    .addComponent(patientLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientBirthdateLabel)
                    .addComponent(patientBirthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderLabel)
                    .addComponent(patientEmailLabel)
                    .addComponent(patientEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPhoneLabel)
                    .addComponent(patientPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAddressLabel)
                    .addComponent(patientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(patientUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(patientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientConfirmPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(patientConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(savePatientProfileButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        patientTabbedPane.addTab("Modify info", patientProfilePanel);

        appointmentRequestTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentRequestTitleLabel.setText("Request medical appointment");

        searchBySpecialtyRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchBySpecialtyRadioButton.setText("Specialty");
        searchBySpecialtyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        searchByDoctorRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchByDoctorRadioButton.setText("Doctor");
        searchByDoctorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        patientProfileSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        appointmentDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentDateLabel.setText("Appointment date");

        appointmentDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        appointmentTimeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        appointmentTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentTimeLabel.setText("Appointment time");

        appointmentTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentTypeLabel.setText("Appointment type");

        appointmentReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentReasonLabel.setText("Appointment reason");

        appointmentTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        requestAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        requestAppointmentButton.setText("Create");
        requestAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        requestSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        hospitalizationRequestTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationRequestTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationRequestTitleLabel.setText("Request hospitalization");

        hospitalizationReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationReasonLabel.setText("Hospitalization reason");

        hospitalizationDoctorLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationDoctorLabel.setText("Attending doctor");

        hospitalizationDoctorComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationDoctorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationAdmissionDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        hospitalizationAdmissionDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationAdmissionDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationAdmissionDateLabel.setText("Estimated date of admission");
        hospitalizationAdmissionDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        hospitalizationRoomTypeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationRoomTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationRoomTypeLabel.setText("Desired room type");

        roomTypeComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        roomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationObservationsLabel.setText("Observations");

        hospitalizationObservationsArea.setColumns(20);
        hospitalizationObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsArea.setRows(5);
        hospitalizationObservationsScrollPane.setViewportView(hospitalizationObservationsArea);

        requestHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        requestHospitalizationButton.setText("Create");
        requestHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cancelAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentTitleLabel.setText("Cancel appointment");

        cancelAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentIdLabel.setText("ID appointment");

        cancelAppointmentObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentObservationsLabel.setText("Observations");

        cancelAppointmentObservationsArea.setColumns(20);
        cancelAppointmentObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentObservationsArea.setRows(5);
        cancelObservationsScrollPane.setViewportView(cancelAppointmentObservationsArea);

        cancelAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentButton.setText("Cancel");
        cancelAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        hospitalizationReasonArea.setColumns(20);
        hospitalizationReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonArea.setRows(5);
        hospitalizationReasonScrollPane.setViewportView(hospitalizationReasonArea);

        appointmentReasonArea.setColumns(20);
        appointmentReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentReasonArea.setRows(5);
        appointmentReasonScrollPane.setViewportView(appointmentReasonArea);

        cancelAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        appointmentDoctorOrSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appointmentDoctorOrSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(patientRequestPanel);
        patientRequestPanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(searchBySpecialtyRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchByDoctorRadioButton))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(appointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(appointmentTimeLabel)
                                        .addComponent(appointmentDateLabel)
                                        .addComponent(appointmentDoctorOrSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(appointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(appointmentReasonLabel))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(appointmentTypeLabel))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(appointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(appointmentRequestTitleLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(appointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(requestAppointmentButton)))
                .addGap(69, 69, 69)
                .addComponent(patientProfileSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(requestHospitalizationButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hospitalizationReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hospitalizationReasonScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(hospitalizationRequestTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(hospitalizationDoctorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hospitalizationObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hospitalizationAdmissionDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hospitalizationRoomTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(hospitalizationDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(hospitalizationAdmissionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(requestSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelObservationsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(cancelAppointmentTitleLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(cancelAppointmentButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cancelAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelAppointmentIdLabel)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(cancelAppointmentObservationsLabel)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientProfileSeparator)
            .addComponent(requestSeparator)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hospitalizationRequestTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(hospitalizationReasonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalizationDoctorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalizationDoctorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalizationAdmissionDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalizationAdmissionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(hospitalizationRoomTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(roomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hospitalizationObservationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(requestHospitalizationButton)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(appointmentRequestTitleLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchBySpecialtyRadioButton)
                                    .addComponent(searchByDoctorRadioButton))
                                .addGap(18, 18, 18)
                                .addComponent(appointmentDoctorOrSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmentDateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(appointmentTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(appointmentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appointmentReasonLabel)
                                .addGap(24, 24, 24)
                                .addComponent(appointmentReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cancelAppointmentTitleLabel)
                                .addGap(39, 39, 39)
                                .addComponent(cancelAppointmentIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cancelAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelAppointmentObservationsLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cancelObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(cancelAppointmentButton)))
                        .addGap(18, 18, 18)
                        .addComponent(appointmentTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(appointmentTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(requestAppointmentButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        patientTabbedPane.addTab("Request/Cancel", patientRequestPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(patientRootPanel);
        patientRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientTitleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(patientTabbedPane)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(patientTitleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Response<AppointmentTableDto> response = applicationContext.getAppointmentController()
                .cancelAppointment(cancelAppointmentComboBox.getItemAt(cancelAppointmentComboBox.getSelectedIndex()));
        showResponse(response);
        if (response.isSuccess()) {
            loadViewData();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PatientUpdateRequest request = new PatientUpdateRequest(
                String.valueOf(patientProfile.getId()),
                patientUsernameField.getText(),
                patientFirstnameField.getText(),
                patientLastnameField.getText(),
                patientPasswordField.getText(),
                patientConfirmPasswordField.getText(),
                patientEmailField.getText(),
                patientBirthdateField.getText(),
                patientGenderComboBox.getSelectedIndex() == 2,
                patientPhoneField.getText(),
                patientAddressField.getText()
        );
        Response<PatientProfileDto> response = applicationContext.getPatientController().updatePatient(request);
        showResponse(response);
        if (response.isSuccess()) {
            patientProfile = response.getData();
            loadPatientProfile();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        openFrame(new NewJFrame(applicationContext));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        openFrame(new NewJFrame11(applicationContext, currentSession));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if (searchByDoctorRadioButton.isSelected()) {
            searchByDoctorRadioButton.setSelected(false);
        }

        appointmentDoctorOrSpecialtyComboBox.removeAllItems();

        appointmentDoctorOrSpecialtyComboBox.addItem("Select one");
        for (model.Specialty specialty : model.Specialty.values()) {
            appointmentDoctorOrSpecialtyComboBox.addItem(specialty.displayName());
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        if (searchBySpecialtyRadioButton.isSelected()) {
            searchBySpecialtyRadioButton.setSelected(false);
        }
        appointmentDoctorOrSpecialtyComboBox.removeAllItems();

        appointmentDoctorOrSpecialtyComboBox.addItem("Select one");
        Response<java.util.List<DoctorOptionDto>> response = applicationContext.getTableDataController()
                .getDoctorOptions();
        if (response.isSuccess()) {
            for (DoctorOptionDto doctor : response.getData()) {
                appointmentDoctorOrSpecialtyComboBox.addItem(String.valueOf(doctor.getId()));
            }
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean byDoctor = searchByDoctorRadioButton.isSelected();
        AppointmentRequest request = new AppointmentRequest(
                String.valueOf(patientProfile.getId()),
                byDoctor ? appointmentDoctorOrSpecialtyComboBox.getItemAt(appointmentDoctorOrSpecialtyComboBox.getSelectedIndex()) : "",
                byDoctor ? "" : appointmentDoctorOrSpecialtyComboBox.getItemAt(appointmentDoctorOrSpecialtyComboBox.getSelectedIndex()),
                appointmentDateField.getText(),
                appointmentTimeField.getText(),
                appointmentReasonArea.getText(),
                appointmentTypeComboBox.getSelectedIndex() == 2
        );
        Response<AppointmentTableDto> response = applicationContext.getAppointmentController()
                .requestAppointment(request);
        showResponse(response);
        if (response.isSuccess()) {
            clearAppointmentRequestFields();
            loadViewData();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        loadAppointmentTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        HospitalizationRequest request = new HospitalizationRequest(
                String.valueOf(patientProfile.getId()),
                hospitalizationDoctorComboBox.getItemAt(hospitalizationDoctorComboBox.getSelectedIndex()),
                null,
                hospitalizationAdmissionDateField.getText(),
                hospitalizationReasonArea.getText(),
                roomTypeComboBox.getItemAt(roomTypeComboBox.getSelectedIndex()),
                hospitalizationObservationsArea.getText()
        );
        Response<?> response = applicationContext.getHospitalizationController().requestHospitalization(request);
        showResponse(response);
        if (response.isSuccess()) {
            clearHospitalizationRequestFields();
            loadViewData();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loadPatientProfile() {
        patientFirstnameField.setText(patientProfile.getFirstname());
        patientLastnameField.setText(patientProfile.getLastname());
        patientBirthdateField.setText(patientProfile.getBirthdate());
        patientAddressField.setText(patientProfile.getAddress());
        patientPhoneField.setText(patientProfile.getPhone());
        patientEmailField.setText(patientProfile.getEmail());
        patientUsernameField.setText(patientProfile.getUsername());
        patientGenderComboBox.setSelectedIndex(patientProfile.isGender() ? 2 : 1);
    }

    private void loadViewData() {
        loadDoctorOptions();
        loadRoomTypeOptions();
        loadAppointmentOptions();
        loadAppointmentTable();
    }

    private void loadDoctorOptions() {
        hospitalizationDoctorComboBox.removeAllItems();
        hospitalizationDoctorComboBox.addItem("Select one");
        Response<java.util.List<DoctorOptionDto>> response = applicationContext.getTableDataController()
                .getDoctorOptions();
        if (response.isSuccess()) {
            for (DoctorOptionDto doctor : response.getData()) {
                hospitalizationDoctorComboBox.addItem(String.valueOf(doctor.getId()));
            }
        }
    }

    private void loadRoomTypeOptions() {
        roomTypeComboBox.removeAllItems();
        roomTypeComboBox.addItem("Select one");
        for (model.RoomType roomType : model.RoomType.values()) {
            roomTypeComboBox.addItem(roomType.name());
        }
    }

    private void loadAppointmentOptions() {
        cancelAppointmentComboBox.removeAllItems();
        cancelAppointmentComboBox.addItem("Select one");
        Response<java.util.List<AppointmentTableDto>> response = applicationContext.getAppointmentController()
                .getPatientAppointments(String.valueOf(patientProfile.getId()));
        if (response.isSuccess()) {
            for (AppointmentTableDto appointment : response.getData()) {
                cancelAppointmentComboBox.addItem(appointment.getId());
            }
        }
    }

    private void loadAppointmentTable() {
        Response<java.util.List<AppointmentTableDto>> response = applicationContext.getAppointmentController()
                .getPatientAppointments(String.valueOf(patientProfile.getId()));
        if (!response.isSuccess()) {
            showResponse(response);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientAppointmentsTable.getModel();
        model.setRowCount(0);
        for (AppointmentTableDto appointment : response.getData()) {
            model.addRow(new Object[]{
                appointment.getId(),
                appointment.getDate() + " " + appointment.getTime(),
                appointment.getDoctorName(),
                appointment.getSpecialty(),
                appointment.isInPerson() ? "In-person" : "Remote",
                appointment.getStatus()
            });
        }
    }

    private void openFrame(JFrame frame) {
        this.setVisible(false);
        frame.setVisible(true);
        this.dispose();
    }

    private void showResponse(Response<?> response) {
        JOptionPane.showMessageDialog(this, response.getMessage());
    }

    private void clearAppointmentRequestFields() {
        appointmentDateField.setText("");
        appointmentTimeField.setText("");
        appointmentReasonArea.setText("");
        appointmentTypeComboBox.setSelectedIndex(0);
        appointmentDoctorOrSpecialtyComboBox.setSelectedIndex(0);
    }

    private void clearHospitalizationRequestFields() {
        hospitalizationAdmissionDateField.setText("");
        hospitalizationReasonArea.setText("");
        hospitalizationObservationsArea.setText("");
        hospitalizationDoctorComboBox.setSelectedIndex(0);
        roomTypeComboBox.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton patientCloseButton;
    private javax.swing.JButton requestAppointmentButton;
    private javax.swing.JButton requestHospitalizationButton;
    private javax.swing.JButton cancelAppointmentButton;
    private javax.swing.JButton refreshAppointmentsButton;
    private javax.swing.JButton patientBackButton;
    private javax.swing.JButton patientLogoutButton;
    private javax.swing.JButton savePatientProfileButton;
    private javax.swing.JComboBox<String> appointmentTypeComboBox;
    private javax.swing.JComboBox<String> hospitalizationDoctorComboBox;
    private javax.swing.JComboBox<String> roomTypeComboBox;
    private javax.swing.JComboBox<String> cancelAppointmentComboBox;
    private javax.swing.JComboBox<String> appointmentDoctorOrSpecialtyComboBox;
    private javax.swing.JComboBox<String> patientGenderComboBox;
    private javax.swing.JLabel patientTitleLabel;
    private javax.swing.JLabel patientPasswordLabel;
    private javax.swing.JLabel patientConfirmPasswordLabel;
    private javax.swing.JLabel patientUsernameLabel;
    private javax.swing.JLabel appointmentRequestTitleLabel;
    private javax.swing.JLabel appointmentDateLabel;
    private javax.swing.JLabel appointmentTimeLabel;
    private javax.swing.JLabel appointmentTypeLabel;
    private javax.swing.JLabel appointmentReasonLabel;
    private javax.swing.JLabel hospitalizationRequestTitleLabel;
    private javax.swing.JLabel hospitalizationReasonLabel;
    private javax.swing.JLabel patientFirstnameLabel;
    private javax.swing.JLabel hospitalizationDoctorLabel;
    private javax.swing.JLabel hospitalizationAdmissionDateLabel;
    private javax.swing.JLabel hospitalizationRoomTypeLabel;
    private javax.swing.JLabel hospitalizationObservationsLabel;
    private javax.swing.JLabel cancelAppointmentTitleLabel;
    private javax.swing.JLabel cancelAppointmentIdLabel;
    private javax.swing.JLabel cancelAppointmentObservationsLabel;
    private javax.swing.JLabel patientLastnameLabel;
    private javax.swing.JLabel patientBirthdateLabel;
    private javax.swing.JLabel patientGenderLabel;
    private javax.swing.JLabel patientEmailLabel;
    private javax.swing.JLabel patientPhoneLabel;
    private javax.swing.JLabel patientAddressLabel;
    private javax.swing.JPanel patientProfilePanel;
    private javax.swing.JPanel patientRequestPanel;
    private javax.swing.JPanel patientAppointmentsPanel;
    private javax.swing.JRadioButton searchBySpecialtyRadioButton;
    private javax.swing.JRadioButton searchByDoctorRadioButton;
    private javax.swing.JScrollPane hospitalizationObservationsScrollPane;
    private javax.swing.JScrollPane cancelObservationsScrollPane;
    private javax.swing.JScrollPane appointmentsTableScrollPane;
    private javax.swing.JScrollPane hospitalizationReasonScrollPane;
    private javax.swing.JScrollPane appointmentReasonScrollPane;
    private javax.swing.JSeparator patientProfileSeparator;
    private javax.swing.JSeparator requestSeparator;
    private javax.swing.JTabbedPane patientTabbedPane;
    private javax.swing.JTable patientAppointmentsTable;
    private javax.swing.JTextArea hospitalizationObservationsArea;
    private javax.swing.JTextArea cancelAppointmentObservationsArea;
    private javax.swing.JTextArea hospitalizationReasonArea;
    private javax.swing.JTextArea appointmentReasonArea;
    private javax.swing.JTextField patientFirstnameField;
    private javax.swing.JTextField patientConfirmPasswordField;
    private javax.swing.JTextField patientUsernameField;
    private javax.swing.JTextField appointmentDateField;
    private javax.swing.JTextField appointmentTimeField;
    private javax.swing.JTextField hospitalizationAdmissionDateField;
    private javax.swing.JTextField patientLastnameField;
    private javax.swing.JTextField patientBirthdateField;
    private javax.swing.JTextField patientEmailField;
    private javax.swing.JTextField patientPhoneField;
    private javax.swing.JTextField patientAddressField;
    private javax.swing.JTextField patientPasswordField;
    private packagee.PanelRound patientRootPanel;
    private packagee.PanelRound patientTitleBarPanel;
    // End of variables declaration//GEN-END:variables
}
