/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee;

import app.ApplicationContext;
import dto.AppointmentTableDto;
import dto.AppointmentUpdateRequest;
import dto.DoctorProfileDto;
import dto.DoctorUpdateRequest;
import dto.HospitalizationRequest;
import dto.HospitalizationTableDto;
import dto.PatientOptionDto;
import dto.PrescriptionRequest;
import dto.SessionDto;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import response.Response;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class NewJFrame111 extends javax.swing.JFrame {

    private int x, y;
    private final ApplicationContext applicationContext;
    private final SessionDto currentSession;
    private DoctorProfileDto doctorProfile;

    public NewJFrame111(ApplicationContext applicationContext, SessionDto currentSession,
            DoctorProfileDto doctorProfile) {
        this.applicationContext = applicationContext;
        this.currentSession = currentSession;
        this.doctorProfile = doctorProfile;
        initComponents();
        doctorBackButton.setVisible("ADMIN".equals(currentSession.getRole()));
        loadDoctorProfile();
        loadViewData();
        applicationContext.getEventPublisher().addListener(this::loadViewData);
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorRootPanel = new packagee.PanelRound();
        doctorTitleBarPanel = new packagee.PanelRound();
        doctorCloseButton = new javax.swing.JButton();
        doctorTitleLabel = new javax.swing.JLabel();
        doctorBackButton = new javax.swing.JButton();
        doctorTabbedPane = new javax.swing.JTabbedPane();
        doctorAppointmentsPanel = new javax.swing.JPanel();
        totalAppointmentsRadioButton = new javax.swing.JRadioButton();
        doctorAppointmentsScrollPane = new javax.swing.JScrollPane();
        doctorAppointmentsTable = new javax.swing.JTable();
        pendingAppointmentsRadioButton = new javax.swing.JRadioButton();
        doctorLogoutButton = new javax.swing.JButton();
        patientLookupPanel = new javax.swing.JPanel();
        patientLookupComboBox = new javax.swing.JComboBox<>();
        patientLookupLabel = new javax.swing.JLabel();
        patientAppointmentsScrollPane = new javax.swing.JScrollPane();
        patientAppointmentsTable = new javax.swing.JTable();
        searchPatientAppointmentsButton = new javax.swing.JButton();
        doctorProfilePanel = new javax.swing.JPanel();
        doctorFirstnameLabel = new javax.swing.JLabel();
        doctorFirstnameField = new javax.swing.JTextField();
        doctorLastnameLabel = new javax.swing.JLabel();
        doctorLastnameField = new javax.swing.JTextField();
        doctorSpecialtyLabel = new javax.swing.JLabel();
        doctorLicenseLabel = new javax.swing.JLabel();
        doctorLicenseField = new javax.swing.JTextField();
        doctorOfficeLabel = new javax.swing.JLabel();
        doctorUsernameField = new javax.swing.JTextField();
        doctorUsernameLabel = new javax.swing.JLabel();
        doctorOfficeField = new javax.swing.JTextField();
        doctorPasswordField = new javax.swing.JTextField();
        doctorPasswordLabel = new javax.swing.JLabel();
        doctorConfirmPasswordLabel = new javax.swing.JLabel();
        doctorConfirmPasswordField = new javax.swing.JTextField();
        doctorSpecialtyComboBox = new javax.swing.JComboBox<>();
        saveDoctorProfileButton = new javax.swing.JButton();
        doctorActionsPanel = new javax.swing.JPanel();
        acceptAppointmentIdLabel = new javax.swing.JLabel();
        acceptAppointmentTitleLabel = new javax.swing.JLabel();
        acceptAppointmentComboBox = new javax.swing.JComboBox<>();
        acceptRescheduleSeparator = new javax.swing.JSeparator();
        acceptAppointmentButton = new javax.swing.JButton();
        rescheduleAppointmentTitleLabel = new javax.swing.JLabel();
        rescheduleAppointmentIdLabel = new javax.swing.JLabel();
        rescheduleAppointmentComboBox = new javax.swing.JComboBox<>();
        rescheduleAppointmentButton = new javax.swing.JButton();
        rescheduleTimeLabel = new javax.swing.JLabel();
        rescheduleTimeField = new javax.swing.JTextField();
        rescheduleReasonLabel = new javax.swing.JLabel();
        rescheduleReasonField = new javax.swing.JTextField();
        rescheduleCompleteSeparator = new javax.swing.JSeparator();
        completeAppointmentTitleLabel = new javax.swing.JLabel();
        completeAppointmentIdLabel = new javax.swing.JLabel();
        completeAppointmentComboBox = new javax.swing.JComboBox<>();
        diagnosisLabel = new javax.swing.JLabel();
        completionObservationsLabel = new javax.swing.JLabel();
        recommendedTreatmentLabel = new javax.swing.JLabel();
        followUpLabel = new javax.swing.JLabel();
        completeAppointmentButton = new javax.swing.JButton();
        hospitalizationSectionLabel = new javax.swing.JLabel();
        hospitalizationReasonLabel = new javax.swing.JLabel();
        hospitalizationEntryDateLabel = new javax.swing.JLabel();
        hospitalizationEntryDateField = new javax.swing.JTextField();
        hospitalizationEstimatedDurationLabel = new javax.swing.JLabel();
        hospitalizationEstimatedDurationField = new javax.swing.JTextField();
        hospitalizationObservationsLabel = new javax.swing.JLabel();
        hospitalizationObservationsScrollPane = new javax.swing.JScrollPane();
        hospitalizationObservationsArea = new javax.swing.JTextArea();
        generateHospitalizationButton = new javax.swing.JButton();
        hospitalizationRequestComboBox = new javax.swing.JComboBox<>();
        hospitalizationRequestsRadioButton = new javax.swing.JRadioButton();
        hospitalizationFromAppointmentRadioButton = new javax.swing.JRadioButton();
        diagnosisScrollPane = new javax.swing.JScrollPane();
        diagnosisArea = new javax.swing.JTextArea();
        completionObservationsScrollPane = new javax.swing.JScrollPane();
        completionObservationsArea = new javax.swing.JTextArea();
        recommendedTreatmentScrollPane = new javax.swing.JScrollPane();
        recommendedTreatmentArea = new javax.swing.JTextArea();
        followUpScrollPane = new javax.swing.JScrollPane();
        followUpArea = new javax.swing.JTextArea();
        hospitalizationSeparator = new javax.swing.JSeparator();
        cancelHospitalizationRequestButton = new javax.swing.JButton();
        hospitalizationAppointmentComboBox = new javax.swing.JComboBox<>();
        hospitalizationReasonScrollPane = new javax.swing.JScrollPane();
        hospitalizationReasonArea = new javax.swing.JTextArea();
        prescriptionPanel = new javax.swing.JPanel();
        prescriptionAppointmentIdLabel = new javax.swing.JLabel();
        medicationNameLabel = new javax.swing.JLabel();
        medicationNameField = new javax.swing.JTextField();
        doseLabel = new javax.swing.JLabel();
        doseField = new javax.swing.JTextField();
        administrationRouteLabel = new javax.swing.JLabel();
        administrationRouteField = new javax.swing.JTextField();
        frequencyLabel = new javax.swing.JLabel();
        frequencyField = new javax.swing.JTextField();
        treatmentDurationLabel = new javax.swing.JLabel();
        treatmentDurationField = new javax.swing.JTextField();
        additionalInstructionsLabel = new javax.swing.JLabel();
        additionalInstructionsField = new javax.swing.JTextField();
        prescriptionsTableScrollPane = new javax.swing.JScrollPane();
        prescriptionsTable = new javax.swing.JTable();
        addPrescriptionButton = new javax.swing.JButton();
        prescribeMedicationButton = new javax.swing.JButton();
        prescriptionAppointmentComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        doctorRootPanel.setRadius(50);

        doctorTitleBarPanel.setRadius(50);
        doctorTitleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        doctorTitleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        doctorCloseButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorCloseButton.setText("X");
        doctorCloseButton.setBorderPainted(false);
        doctorCloseButton.setContentAreaFilled(false);
        doctorCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        doctorCloseButton.setFocusable(false);
        doctorCloseButton.setRequestFocusEnabled(false);
        doctorCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        doctorTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        doctorTitleLabel.setText("DOCTOR VIEW");

        doctorBackButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorBackButton.setText("Back");
        doctorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(doctorTitleBarPanel);
        doctorTitleBarPanel.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctorTitleLabel)
                .addGap(32, 32, 32)
                .addComponent(doctorBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doctorCloseButton)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(doctorCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doctorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(doctorBackButton))
        );

        totalAppointmentsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        totalAppointmentsRadioButton.setText("Total appointments");
        totalAppointmentsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        doctorAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        doctorAppointmentsScrollPane.setViewportView(doctorAppointmentsTable);

        pendingAppointmentsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        pendingAppointmentsRadioButton.setText("Pending appointments");
        pendingAppointmentsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        doctorLogoutButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLogoutButton.setText("Logout");
        doctorLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(doctorAppointmentsPanel);
        doctorAppointmentsPanel.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doctorLogoutButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(totalAppointmentsRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(pendingAppointmentsRadioButton))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(doctorAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAppointmentsRadioButton)
                    .addComponent(pendingAppointmentsRadioButton))
                .addGap(18, 18, 18)
                .addComponent(doctorAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(doctorLogoutButton)
                .addGap(23, 23, 23))
        );

        doctorTabbedPane.addTab("Appointments visualization", doctorAppointmentsPanel);

        patientLookupComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLookupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        patientLookupLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patientLookupLabel.setText("Patient");

        patientAppointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientAppointmentsScrollPane.setViewportView(patientAppointmentsTable);

        searchPatientAppointmentsButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        searchPatientAppointmentsButton.setText("Search");
        searchPatientAppointmentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(patientLookupPanel);
        patientLookupPanel.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(patientLookupLabel)
                        .addGap(18, 18, 18)
                        .addComponent(patientLookupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(patientAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchPatientAppointmentsButton)
                .addGap(601, 601, 601))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLookupLabel)
                    .addComponent(patientLookupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(patientAppointmentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(searchPatientAppointmentsButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        doctorTabbedPane.addTab("History Appointments of a patient", patientLookupPanel);

        doctorFirstnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorFirstnameLabel.setText("Firstname");

        doctorFirstnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorLastnameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLastnameLabel.setText("Lastname");

        doctorLastnameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorSpecialtyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSpecialtyLabel.setText("Specialty");

        doctorLicenseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorLicenseLabel.setText("License Number");

        doctorLicenseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorOfficeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorOfficeLabel.setText("Assigned office");

        doctorUsernameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorUsernameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorUsernameLabel.setText("User");

        doctorOfficeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorPasswordLabel.setText("Password");

        doctorConfirmPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorConfirmPasswordLabel.setText("Password confirmation");

        doctorConfirmPasswordField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doctorSpecialtyComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctorSpecialtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        saveDoctorProfileButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        saveDoctorProfileButton.setText("Save");
        saveDoctorProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(doctorProfilePanel);
        doctorProfilePanel.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(doctorFirstnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorLastnameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorSpecialtyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(doctorLicenseLabel)
                        .addGap(18, 18, 18)
                        .addComponent(doctorLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(doctorOfficeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(doctorUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(doctorUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doctorPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(doctorConfirmPasswordLabel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(saveDoctorProfileButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(doctorConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorFirstnameLabel)
                    .addComponent(doctorFirstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorLastnameLabel)
                    .addComponent(doctorLastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorSpecialtyLabel)
                    .addComponent(doctorSpecialtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorLicenseLabel)
                    .addComponent(doctorLicenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorOfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorOfficeLabel))
                .addGap(30, 30, 30)
                .addComponent(doctorUsernameLabel)
                .addGap(18, 18, 18)
                .addComponent(doctorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorPasswordLabel)
                .addGap(27, 27, 27)
                .addComponent(doctorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorConfirmPasswordLabel)
                .addGap(18, 18, 18)
                .addComponent(doctorConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(saveDoctorProfileButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        doctorTabbedPane.addTab("Modify info", doctorProfilePanel);

        acceptAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceptAppointmentIdLabel.setText("Appointment ID");

        acceptAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentTitleLabel.setText("Accept medical appointment");

        acceptAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        acceptRescheduleSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        acceptAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        acceptAppointmentButton.setText("Accept");
        acceptAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rescheduleAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleAppointmentTitleLabel.setText("Reschedule medical appointment");

        rescheduleAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleAppointmentIdLabel.setText("Appointment");

        rescheduleAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        rescheduleAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleAppointmentButton.setText("Accept");
        rescheduleAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        rescheduleTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleTimeLabel.setText("New time appointment");

        rescheduleTimeField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        rescheduleReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rescheduleReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rescheduleReasonLabel.setText("Reason for appointment");

        rescheduleReasonField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        rescheduleCompleteSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        completeAppointmentTitleLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completeAppointmentTitleLabel.setText("Complete medical appointment");

        completeAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completeAppointmentIdLabel.setText("Appointment");

        completeAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        diagnosisLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        diagnosisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diagnosisLabel.setText("Diagnosis");

        completionObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completionObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completionObservationsLabel.setText("Observations");

        recommendedTreatmentLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        recommendedTreatmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recommendedTreatmentLabel.setText("Recommended treatment");

        followUpLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        followUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        followUpLabel.setText("Follow-up indication");

        completeAppointmentButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completeAppointmentButton.setText("Complete");
        completeAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        hospitalizationSectionLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationSectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationSectionLabel.setText("Hospitalization");

        hospitalizationReasonLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationReasonLabel.setText("Reason for hospitalization");

        hospitalizationEntryDateLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationEntryDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationEntryDateLabel.setText("Date of entry");

        hospitalizationEntryDateField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        hospitalizationEstimatedDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationEstimatedDurationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationEstimatedDurationLabel.setText("Estimated duration");

        hospitalizationEstimatedDurationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        hospitalizationObservationsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hospitalizationObservationsLabel.setText("Observations");

        hospitalizationObservationsArea.setColumns(20);
        hospitalizationObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationObservationsArea.setRows(5);
        hospitalizationObservationsScrollPane.setViewportView(hospitalizationObservationsArea);

        generateHospitalizationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        generateHospitalizationButton.setText("Generate");
        generateHospitalizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        hospitalizationRequestComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationRequestComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationRequestsRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationRequestsRadioButton.setText("Requests");

        hospitalizationFromAppointmentRadioButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationFromAppointmentRadioButton.setText("Patient ID");

        diagnosisArea.setColumns(20);
        diagnosisArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        diagnosisArea.setRows(5);
        diagnosisScrollPane.setViewportView(diagnosisArea);

        completionObservationsArea.setColumns(20);
        completionObservationsArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        completionObservationsArea.setRows(5);
        completionObservationsScrollPane.setViewportView(completionObservationsArea);

        recommendedTreatmentArea.setColumns(20);
        recommendedTreatmentArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        recommendedTreatmentArea.setRows(5);
        recommendedTreatmentScrollPane.setViewportView(recommendedTreatmentArea);

        followUpArea.setColumns(20);
        followUpArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        followUpArea.setRows(5);
        followUpScrollPane.setViewportView(followUpArea);

        hospitalizationSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cancelHospitalizationRequestButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cancelHospitalizationRequestButton.setText("Cancel");
        cancelHospitalizationRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        hospitalizationAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        hospitalizationReasonArea.setColumns(20);
        hospitalizationReasonArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        hospitalizationReasonArea.setRows(5);
        hospitalizationReasonScrollPane.setViewportView(hospitalizationReasonArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(doctorActionsPanel);
        doctorActionsPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(acceptAppointmentButton)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(acceptAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(acceptAppointmentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(acceptRescheduleSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(acceptAppointmentTitleLabel)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rescheduleAppointmentTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rescheduleAppointmentIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rescheduleTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rescheduleReasonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(rescheduleAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(rescheduleTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(rescheduleReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(rescheduleAppointmentButton)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rescheduleCompleteSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(completeAppointmentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(completeAppointmentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(completeAppointmentTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(completeAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 25, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diagnosisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(completionObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(followUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(recommendedTreatmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(diagnosisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(completionObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(recommendedTreatmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(followUpScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(hospitalizationSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalizationSectionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hospitalizationEntryDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hospitalizationEstimatedDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hospitalizationObservationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalizationEntryDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hospitalizationEstimatedDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cancelHospitalizationRequestButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateHospitalizationButton))
                            .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hospitalizationRequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(hospitalizationRequestsRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(hospitalizationFromAppointmentRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(hospitalizationAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hospitalizationReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acceptRescheduleSeparator)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rescheduleCompleteSeparator)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(completeAppointmentTitleLabel)
                        .addGap(10, 10, 10)
                        .addComponent(completeAppointmentIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(completeAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diagnosisLabel)
                        .addGap(18, 18, 18)
                        .addComponent(diagnosisScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(completionObservationsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(completionObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(recommendedTreatmentLabel)
                        .addGap(18, 18, 18)
                        .addComponent(recommendedTreatmentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(followUpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(followUpScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(completeAppointmentButton)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(acceptAppointmentTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(acceptAppointmentIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(acceptAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(acceptAppointmentButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(rescheduleAppointmentTitleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleAppointmentIdLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleTimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleReasonLabel)
                                .addGap(18, 18, 18)
                                .addComponent(rescheduleReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rescheduleAppointmentButton)))
                        .addGap(18, 18, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(hospitalizationSectionLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalizationRequestsRadioButton)
                    .addComponent(hospitalizationFromAppointmentRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalizationRequestComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalizationAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hospitalizationReasonLabel)
                .addGap(16, 16, 16)
                .addComponent(hospitalizationReasonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospitalizationEntryDateLabel)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationEntryDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationEstimatedDurationLabel)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationEstimatedDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationObservationsLabel)
                .addGap(18, 18, 18)
                .addComponent(hospitalizationObservationsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateHospitalizationButton)
                    .addComponent(cancelHospitalizationRequestButton))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(hospitalizationSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        doctorTabbedPane.addTab("Request/Appointments", doctorActionsPanel);

        prescriptionAppointmentIdLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        prescriptionAppointmentIdLabel.setText("Appointment ID");

        medicationNameLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        medicationNameLabel.setText("Medication name");

        medicationNameField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        doseLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doseLabel.setText("Dose");

        doseField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        administrationRouteLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        administrationRouteLabel.setText("Administration route");

        administrationRouteField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        frequencyLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        frequencyLabel.setText("Frecuency");

        frequencyField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        treatmentDurationLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        treatmentDurationLabel.setText("Treatment duration");

        treatmentDurationField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        additionalInstructionsLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        additionalInstructionsLabel.setText("Additional instructions");

        additionalInstructionsField.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        prescriptionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prescriptionsTableScrollPane.setViewportView(prescriptionsTable);

        addPrescriptionButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        addPrescriptionButton.setText("Add");
        addPrescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        prescribeMedicationButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        prescribeMedicationButton.setText("Prescribe");
        prescribeMedicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        prescriptionAppointmentComboBox.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        prescriptionAppointmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(prescriptionPanel);
        prescriptionPanel.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prescriptionsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(prescriptionAppointmentIdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(prescriptionAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(medicationNameLabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(treatmentDurationLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(treatmentDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(additionalInstructionsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(additionalInstructionsField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(frequencyLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(medicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(doseField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(administrationRouteLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(administrationRouteField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addPrescriptionButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(prescribeMedicationButton)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prescriptionAppointmentIdLabel)
                    .addComponent(medicationNameLabel)
                    .addComponent(medicationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doseLabel)
                    .addComponent(doseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administrationRouteLabel)
                    .addComponent(administrationRouteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPrescriptionButton)
                    .addComponent(prescriptionAppointmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treatmentDurationLabel)
                    .addComponent(treatmentDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additionalInstructionsLabel)
                    .addComponent(additionalInstructionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frequencyLabel)
                    .addComponent(frequencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(prescriptionsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(prescribeMedicationButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        doctorTabbedPane.addTab("Prescribe medications", prescriptionPanel);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(doctorRootPanel);
        doctorRootPanel.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doctorTitleBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorTabbedPane))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(doctorTitleBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorTabbedPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorRootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        totalAppointmentsRadioButton.setSelected(false);
        loadDoctorAppointmentTable(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        DoctorUpdateRequest request = new DoctorUpdateRequest(
                String.valueOf(doctorProfile.getId()),
                doctorUsernameField.getText(),
                doctorFirstnameField.getText(),
                doctorLastnameField.getText(),
                doctorPasswordField.getText(),
                doctorConfirmPasswordField.getText(),
                doctorSpecialtyComboBox.getItemAt(doctorSpecialtyComboBox.getSelectedIndex()),
                doctorLicenseField.getText(),
                doctorOfficeField.getText()
        );
        Response<DoctorProfileDto> response = applicationContext.getDoctorController().updateDoctor(request);
        showResponse(response);
        if (response.isSuccess()) {
            doctorProfile = response.getData();
            loadDoctorProfile();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        openFrame(new NewJFrame(applicationContext));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        openFrame(new NewJFrame11(applicationContext, currentSession));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (hospitalizationRequestsRadioButton.isSelected()) {
            Response<HospitalizationTableDto> response = applicationContext.getHospitalizationController()
                    .denyHospitalization(hospitalizationRequestComboBox.getItemAt(hospitalizationRequestComboBox.getSelectedIndex()));
            showResponse(response);
            if (response.isSuccess()) {
                loadViewData();
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (hospitalizationFromAppointmentRadioButton.isSelected()) {
            HospitalizationRequest request = new HospitalizationRequest(
                    null,
                    String.valueOf(doctorProfile.getId()),
                    hospitalizationAppointmentComboBox.getItemAt(hospitalizationAppointmentComboBox.getSelectedIndex()),
                    hospitalizationEntryDateField.getText(),
                    hospitalizationReasonArea.getText(),
                    null,
                    hospitalizationObservationsArea.getText()
            );
            Response<HospitalizationTableDto> response = applicationContext.getHospitalizationController()
                    .createHospitalizationFromAppointment(request);
            showResponse(response);
            if (response.isSuccess()) {
                clearHospitalizationFields();
                loadViewData();
            }
            return;
        }
        if (hospitalizationRequestsRadioButton.isSelected()) {
            Response<HospitalizationTableDto> response = applicationContext.getHospitalizationController()
                    .approveHospitalization(hospitalizationRequestComboBox.getItemAt(hospitalizationRequestComboBox.getSelectedIndex()));
            showResponse(response);
            if (response.isSuccess()) {
                clearHospitalizationFields();
                loadViewData();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        loadPatientAppointmentTable(patientLookupComboBox.getItemAt(patientLookupComboBox.getSelectedIndex()));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        pendingAppointmentsRadioButton.setSelected(false);
        loadDoctorAppointmentTable(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Response<AppointmentTableDto> response = applicationContext.getAppointmentController()
                .acceptAppointment(acceptAppointmentComboBox.getItemAt(acceptAppointmentComboBox.getSelectedIndex()),
                        String.valueOf(doctorProfile.getId()));
        showResponse(response);
        if (response.isSuccess()) {
            loadViewData();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AppointmentUpdateRequest request = new AppointmentUpdateRequest(
                completeAppointmentComboBox.getItemAt(completeAppointmentComboBox.getSelectedIndex()),
                String.valueOf(doctorProfile.getId()),
                null,
                null,
                false,
                diagnosisArea.getText(),
                completionObservationsArea.getText(),
                recommendedTreatmentArea.getText(),
                followUpArea.getText()
        );
        Response<AppointmentTableDto> response = applicationContext.getAppointmentController()
                .completeAppointment(request);
        showResponse(response);
        if (response.isSuccess()) {
            clearCompleteAppointmentFields();
            loadViewData();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model = (DefaultTableModel) prescriptionsTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        PrescriptionRequest request = new PrescriptionRequest(
                prescriptionAppointmentComboBox.getItemAt(prescriptionAppointmentComboBox.getSelectedIndex()),
                String.valueOf(doctorProfile.getId()),
                medicationNameField.getText(),
                doseField.getText(),
                administrationRouteField.getText(),
                treatmentDurationField.getText(),
                additionalInstructionsField.getText(),
                frequencyField.getText()
        );
        Response<AppointmentTableDto> response = applicationContext.getPrescriptionController().prescribe(request);
        showResponse(response);
        if (response.isSuccess()) {
            DefaultTableModel model = (DefaultTableModel) prescriptionsTable.getModel();
            model.addRow(new Object[]{
                request.getAppointmentId(),
                request.getMedicationName(),
                request.getDose(),
                request.getAdministrationRoute(),
                String.valueOf(request.getTreatmentDuration()),
                request.getAdditionalInstructions(),
                String.valueOf(request.getFrequency())
            });
            clearPrescriptionFields();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AppointmentUpdateRequest request = new AppointmentUpdateRequest(
                rescheduleAppointmentComboBox.getItemAt(rescheduleAppointmentComboBox.getSelectedIndex()),
                String.valueOf(doctorProfile.getId()),
                rescheduleTimeField.getText(),
                rescheduleReasonField.getText(),
                false,
                null,
                null,
                null,
                null
        );
        Response<AppointmentTableDto> response = applicationContext.getAppointmentController()
                .rescheduleAppointment(request);
        showResponse(response);
        if (response.isSuccess()) {
            clearRescheduleFields();
            loadViewData();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loadDoctorProfile() {
        doctorFirstnameField.setText(doctorProfile.getFirstname());
        doctorLastnameField.setText(doctorProfile.getLastname());
        doctorLicenseField.setText(doctorProfile.getLicenceNumber());
        doctorOfficeField.setText(doctorProfile.getAssignedOffice());
        doctorUsernameField.setText(doctorProfile.getUsername());
        selectComboValue(doctorSpecialtyComboBox, doctorProfile.getSpecialty());
    }

    private void loadViewData() {
        loadDoctorAppointmentTable(pendingAppointmentsRadioButton.isSelected());
        loadAppointmentOptions();
        loadPatientOptions();
        loadHospitalizationOptions();
    }

    private void loadDoctorAppointmentTable(boolean pendingOnly) {
        Response<java.util.List<AppointmentTableDto>> response = applicationContext.getAppointmentController()
                .getDoctorAppointments(String.valueOf(doctorProfile.getId()), pendingOnly);
        if (!response.isSuccess()) {
            showResponse(response);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) doctorAppointmentsTable.getModel();
        model.setRowCount(0);
        for (AppointmentTableDto appointment : response.getData()) {
            model.addRow(new Object[]{
                appointment.getId(),
                appointment.getDate() + " " + appointment.getTime(),
                appointment.getPatientName(),
                appointment.getSpecialty(),
                appointment.isInPerson() ? "In-person" : "Remote",
                appointment.getStatus()
            });
        }
    }

    private void loadPatientAppointmentTable(String patientId) {
        Response<java.util.List<AppointmentTableDto>> response = applicationContext.getAppointmentController()
                .getPatientAppointments(patientId);
        if (!response.isSuccess()) {
            showResponse(response);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientAppointmentsTable.getModel();
        model.setRowCount(0);
        for (AppointmentTableDto appointment : response.getData()) {
            model.addRow(new Object[]{
                appointment.getId(),
                appointment.getDate() + " " + appointment.getTime(),
                appointment.getDoctorName(),
                appointment.getSpecialty(),
                appointment.isInPerson() ? "In-person" : "Remote",
                appointment.getStatus()
            });
        }
    }

    private void loadAppointmentOptions() {
        acceptAppointmentComboBox.removeAllItems();
        rescheduleAppointmentComboBox.removeAllItems();
        completeAppointmentComboBox.removeAllItems();
        prescriptionAppointmentComboBox.removeAllItems();
        hospitalizationAppointmentComboBox.removeAllItems();
        acceptAppointmentComboBox.addItem("Select one");
        rescheduleAppointmentComboBox.addItem("Select one");
        completeAppointmentComboBox.addItem("Select one");
        prescriptionAppointmentComboBox.addItem("Select one");
        hospitalizationAppointmentComboBox.addItem("Select one");

        Response<java.util.List<AppointmentTableDto>> all = applicationContext.getAppointmentController()
                .getDoctorAppointments(String.valueOf(doctorProfile.getId()), false);
        if (!all.isSuccess()) {
            return;
        }
        for (AppointmentTableDto appointment : all.getData()) {
            acceptAppointmentComboBox.addItem(appointment.getId());
            rescheduleAppointmentComboBox.addItem(appointment.getId());
            if ("PENDING".equals(appointment.getStatus())) {
                completeAppointmentComboBox.addItem(appointment.getId());
                prescriptionAppointmentComboBox.addItem(appointment.getId());
                hospitalizationAppointmentComboBox.addItem(appointment.getId());
            }
        }
    }

    private void loadPatientOptions() {
        patientLookupComboBox.removeAllItems();
        patientLookupComboBox.addItem("Select one");
        Response<java.util.List<PatientOptionDto>> response = applicationContext.getTableDataController()
                .getPatientOptions();
        if (response.isSuccess()) {
            for (PatientOptionDto patient : response.getData()) {
                patientLookupComboBox.addItem(String.valueOf(patient.getId()));
            }
        }
    }

    private void loadHospitalizationOptions() {
        hospitalizationRequestComboBox.removeAllItems();
        hospitalizationRequestComboBox.addItem("Select one");
        Response<java.util.List<HospitalizationTableDto>> response = applicationContext.getTableDataController()
                .getHospitalizationTable();
        if (!response.isSuccess()) {
            return;
        }
        for (HospitalizationTableDto hospitalization : response.getData()) {
            if ("REQUESTED".equals(hospitalization.getStatus())
                    && hospitalization.getDoctorId() == doctorProfile.getId()) {
                hospitalizationRequestComboBox.addItem(hospitalization.getId());
            }
        }
    }

    private void openFrame(JFrame frame) {
        this.setVisible(false);
        frame.setVisible(true);
        this.dispose();
    }

    private void showResponse(Response<?> response) {
        JOptionPane.showMessageDialog(this, response.getMessage());
    }

    private void selectComboValue(javax.swing.JComboBox<String> comboBox, String value) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (comboBox.getItemAt(i).equals(value)) {
                comboBox.setSelectedIndex(i);
                return;
            }
        }
        comboBox.setSelectedIndex(0);
    }

    private void clearHospitalizationFields() {
        hospitalizationReasonArea.setText("");
        hospitalizationObservationsArea.setText("");
        hospitalizationEntryDateField.setText("");
        hospitalizationEstimatedDurationField.setText("");
        hospitalizationRequestComboBox.setSelectedIndex(0);
        hospitalizationAppointmentComboBox.setSelectedIndex(0);
    }

    private void clearCompleteAppointmentFields() {
        diagnosisArea.setText("");
        completionObservationsArea.setText("");
        recommendedTreatmentArea.setText("");
        followUpArea.setText("");
        completeAppointmentComboBox.setSelectedIndex(0);
    }

    private void clearPrescriptionFields() {
        medicationNameField.setText("");
        doseField.setText("");
        administrationRouteField.setText("");
        frequencyField.setText("");
        treatmentDurationField.setText("");
        additionalInstructionsField.setText("");
        prescriptionAppointmentComboBox.setSelectedIndex(0);
    }

    private void clearRescheduleFields() {
        rescheduleTimeField.setText("");
        rescheduleReasonField.setText("");
        rescheduleAppointmentComboBox.setSelectedIndex(0);
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctorCloseButton;
    private javax.swing.JButton prescribeMedicationButton;
    private javax.swing.JButton doctorBackButton;
    private javax.swing.JButton doctorLogoutButton;
    private javax.swing.JButton cancelHospitalizationRequestButton;
    private javax.swing.JButton acceptAppointmentButton;
    private javax.swing.JButton rescheduleAppointmentButton;
    private javax.swing.JButton completeAppointmentButton;
    private javax.swing.JButton generateHospitalizationButton;
    private javax.swing.JButton addPrescriptionButton;
    private javax.swing.JButton searchPatientAppointmentsButton;
    private javax.swing.JButton saveDoctorProfileButton;
    private javax.swing.JComboBox<String> doctorSpecialtyComboBox;
    private javax.swing.JComboBox<String> acceptAppointmentComboBox;
    private javax.swing.JComboBox<String> rescheduleAppointmentComboBox;
    private javax.swing.JComboBox<String> completeAppointmentComboBox;
    private javax.swing.JComboBox<String> patientLookupComboBox;
    private javax.swing.JComboBox<String> hospitalizationRequestComboBox;
    private javax.swing.JComboBox<String> prescriptionAppointmentComboBox;
    private javax.swing.JComboBox<String> hospitalizationAppointmentComboBox;
    private javax.swing.JLabel doctorTitleLabel;
    private javax.swing.JLabel doctorPasswordLabel;
    private javax.swing.JLabel doctorConfirmPasswordLabel;
    private javax.swing.JLabel acceptAppointmentTitleLabel;
    private javax.swing.JLabel acceptAppointmentIdLabel;
    private javax.swing.JLabel rescheduleAppointmentTitleLabel;
    private javax.swing.JLabel rescheduleAppointmentIdLabel;
    private javax.swing.JLabel rescheduleTimeLabel;
    private javax.swing.JLabel rescheduleReasonLabel;
    private javax.swing.JLabel completeAppointmentTitleLabel;
    private javax.swing.JLabel doctorFirstnameLabel;
    private javax.swing.JLabel completeAppointmentIdLabel;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JLabel completionObservationsLabel;
    private javax.swing.JLabel recommendedTreatmentLabel;
    private javax.swing.JLabel followUpLabel;
    private javax.swing.JLabel hospitalizationSectionLabel;
    private javax.swing.JLabel hospitalizationReasonLabel;
    private javax.swing.JLabel hospitalizationEntryDateLabel;
    private javax.swing.JLabel hospitalizationEstimatedDurationLabel;
    private javax.swing.JLabel doctorLastnameLabel;
    private javax.swing.JLabel hospitalizationObservationsLabel;
    private javax.swing.JLabel prescriptionAppointmentIdLabel;
    private javax.swing.JLabel medicationNameLabel;
    private javax.swing.JLabel doseLabel;
    private javax.swing.JLabel administrationRouteLabel;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JLabel treatmentDurationLabel;
    private javax.swing.JLabel additionalInstructionsLabel;
    private javax.swing.JLabel patientLookupLabel;
    private javax.swing.JLabel doctorSpecialtyLabel;
    private javax.swing.JLabel doctorLicenseLabel;
    private javax.swing.JLabel doctorOfficeLabel;
    private javax.swing.JLabel doctorUsernameLabel;
    private javax.swing.JPanel doctorActionsPanel;
    private javax.swing.JPanel prescriptionPanel;
    private javax.swing.JPanel doctorProfilePanel;
    private javax.swing.JPanel doctorAppointmentsPanel;
    private javax.swing.JPanel patientLookupPanel;
    private javax.swing.JRadioButton totalAppointmentsRadioButton;
    private javax.swing.JRadioButton pendingAppointmentsRadioButton;
    private javax.swing.JRadioButton hospitalizationRequestsRadioButton;
    private javax.swing.JRadioButton hospitalizationFromAppointmentRadioButton;
    private javax.swing.JScrollPane hospitalizationObservationsScrollPane;
    private javax.swing.JScrollPane hospitalizationReasonScrollPane;
    private javax.swing.JScrollPane prescriptionsTableScrollPane;
    private javax.swing.JScrollPane doctorAppointmentsScrollPane;
    private javax.swing.JScrollPane patientAppointmentsScrollPane;
    private javax.swing.JScrollPane diagnosisScrollPane;
    private javax.swing.JScrollPane completionObservationsScrollPane;
    private javax.swing.JScrollPane recommendedTreatmentScrollPane;
    private javax.swing.JScrollPane followUpScrollPane;
    private javax.swing.JSeparator acceptRescheduleSeparator;
    private javax.swing.JSeparator rescheduleCompleteSeparator;
    private javax.swing.JSeparator hospitalizationSeparator;
    private javax.swing.JTabbedPane doctorTabbedPane;
    private javax.swing.JTable prescriptionsTable;
    private javax.swing.JTable doctorAppointmentsTable;
    private javax.swing.JTable patientAppointmentsTable;
    private javax.swing.JTextArea hospitalizationObservationsArea;
    private javax.swing.JTextArea diagnosisArea;
    private javax.swing.JTextArea completionObservationsArea;
    private javax.swing.JTextArea recommendedTreatmentArea;
    private javax.swing.JTextArea followUpArea;
    private javax.swing.JTextArea hospitalizationReasonArea;
    private javax.swing.JTextField doctorFirstnameField;
    private javax.swing.JTextField doctorConfirmPasswordField;
    private javax.swing.JTextField rescheduleTimeField;
    private javax.swing.JTextField rescheduleReasonField;
    private javax.swing.JTextField doctorLastnameField;
    private javax.swing.JTextField hospitalizationEntryDateField;
    private javax.swing.JTextField hospitalizationEstimatedDurationField;
    private javax.swing.JTextField medicationNameField;
    private javax.swing.JTextField doseField;
    private javax.swing.JTextField administrationRouteField;
    private javax.swing.JTextField frequencyField;
    private javax.swing.JTextField treatmentDurationField;
    private javax.swing.JTextField additionalInstructionsField;
    private javax.swing.JTextField doctorLicenseField;
    private javax.swing.JTextField doctorUsernameField;
    private javax.swing.JTextField doctorOfficeField;
    private javax.swing.JTextField doctorPasswordField;
    private packagee.PanelRound doctorRootPanel;
    private packagee.PanelRound doctorTitleBarPanel;
    // End of variables declaration//GEN-END:variables
}
